# Generated by Django 4.2.1 on 2023-10-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_customuser_name_customuser_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
