# Generated by Django 4.2.1 on 2023-10-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('C Programming', 'C Programming'), ('Office Automation Tools', 'Office Automation Tools'), ('Computer Fundamentals', 'Computer Fundamentals'), ('English', 'English'), ('Maths', 'Maths')], default=None, max_length=100),
        ),
    ]
