# Generated by Django 4.2.1 on 2023-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_note_author_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
