# Generated by Django 4.2.5 on 2024-01-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='question',
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skills')),
            ],
        ),
    ]
