# Generated by Django 4.2.5 on 2024-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_skills_answer_remove_skills_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldetail',
            name='paragraph',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
