# Generated by Django 4.2.5 on 2024-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_skilldetail_paragraph_alter_skills_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
